# github action that checks code with Rector
name: Code Check

on:
    push:
    pull_request:

jobs:
    php-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Laravel Pint
              uses: aglipanci/laravel-pint-action@v2
              with:
                  verboseMode: true
                  testMode: true
                  configPath: ./pint.json

    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                php-version: 8.4
                coverage: none

            - name: Install dependencies
              run: composer install --no-interaction

            - name: Check for Rector fixes
              # Run "composer fix" locally to apply what this finds.
              run: vendor/bin/rector --dry-run --no-progress-bar --ansi

            - uses: php-actions/phpstan@v3
